return {
    Title = "敬重强者·后端修复版",
    Author = "wwkk208",
    Version = "2.0.0.0",
    Description = "按当前多 DLL 后端架构修复旧版 RespectTheStrongBackend。各功能独立探测，版本不兼容时只禁用对应功能。",
    Source = 0,
    GameVersion = "1.0.40",
    BackendPlugins = {
        [1] = "RespectTheStrongBackend.dll",
    },
    TagList = {
        [1] = "Modifications",
        [2] = "Utilities",
    },
    Visibility = 2,
    DefaultSettings = {
        { SettingType = "Toggle", Key = "FixGrowingSectGrade", DisplayName = "固定成长门派品级", GroupName = "人物生成", DefaultValue = false },
        { SettingType = "Slider", Key = "GrowingSectGrade", DisplayName = "成长门派品级", GroupName = "人物生成", MinValue = 0, MaxValue = 8, StepSize = 1, DefaultValue = 8 },
        { SettingType = "Slider", Key = "CustomSpan", DisplayName = "人物属性随机跨度（%）", GroupName = "人物生成", MinValue = 0, MaxValue = 100, StepSize = 5, DefaultValue = 20 },
        { SettingType = "Slider", Key = "GlobalCombatSkillScale", DisplayName = "全局武学资质倍率（%）", GroupName = "人物生成", MinValue = 0, MaxValue = 300, StepSize = 10, DefaultValue = 100 },
        { SettingType = "Slider", Key = "GlobalLifeSkillScale", DisplayName = "全局技艺资质倍率（%）", GroupName = "人物生成", MinValue = 0, MaxValue = 300, StepSize = 10, DefaultValue = 100 },
        { SettingType = "Slider", Key = "GlobalMainAttributeScale", DisplayName = "全局主属性倍率（%）", GroupName = "人物生成", MinValue = 0, MaxValue = 300, StepSize = 10, DefaultValue = 100 },
        { SettingType = "InputField", Key = "HeroProb", DisplayName = "天才概率（万分比）", GroupName = "天才人物", DefaultValue = "0" },
        { SettingType = "InputField", Key = "HeroCombatSkillBonus", DisplayName = "天才武学资质加值", GroupName = "天才人物", DefaultValue = "0" },
        { SettingType = "InputField", Key = "HeroLifeSkillBonus", DisplayName = "天才技艺资质加值", GroupName = "天才人物", DefaultValue = "0" },
        { SettingType = "InputField", Key = "HeroMainAttributeBonus", DisplayName = "天才主属性加值", GroupName = "天才人物", DefaultValue = "0" },
        { SettingType = "Toggle", Key = "HeroPerfectFeature", DisplayName = "天才基础特性升至同组最高级", GroupName = "天才人物", DefaultValue = false },
        { SettingType = "Toggle", Key = "NpcNoBreakoutInjury", DisplayName = "NPC 突破不受伤", GroupName = "NPC 行为", DefaultValue = false },
        { SettingType = "Toggle", Key = "PragmaticNpc", DisplayName = "NPC 不挑剔礼物", GroupName = "NPC 行为", DefaultValue = false },
        { SettingType = "Toggle", Key = "NpcCopyCombatSkillBook", DisplayName = "NPC 学武后获得秘籍", GroupName = "NPC 行为", DefaultValue = false },
        { SettingType = "Toggle", Key = "NpcCopyLifeSkillBook", DisplayName = "NPC 学艺后获得秘籍", GroupName = "NPC 行为", DefaultValue = false },
        { SettingType = "Toggle", Key = "NeiliAdjust", DisplayName = "内力相性调整（兼容项）", GroupName = "NPC 行为", Description = "旧版源码只读取此设置但从未使用；保留设置键，不对当前游戏施加未知改动。", DefaultValue = false },
        { SettingType = "Toggle", Key = "NewPromotionRule", DisplayName = "启用强者晋升规则", GroupName = "组织晋升", DefaultValue = false },
        { SettingType = "Toggle", Key = "ImproveSkillChoiceLogic", DisplayName = "改进 NPC 功法选择", GroupName = "NPC 行为", Description = "当前游戏已内置新版评分公式；本项保留兼容键并避免重复加分。", DefaultValue = false },
        { SettingType = "Toggle", Key = "ImproveOrganizationEquipment", DisplayName = "强化高阶组织成员装备", GroupName = "组织晋升", Description = "恢复旧版的九个高阶成员装备表；关闭或卸载时恢复原配置。", DefaultValue = false },
        { SettingType = "Toggle", Key = "EnableDebugLog", DisplayName = "输出诊断日志", GroupName = "诊断", DefaultValue = false },
    },
    ChangeConfig = false,
    HasArchive = false,
    NeedRestartWhenSettingChanged = false,
}
