return {
    Title = "人物工坊[测试版]",
    Author = "WQHH",
    Version = "0.5.0-test",
    Description = "[h1]人物工坊[测试版][/h1]\n\n[b]主要功能[/b]\n[list]\n[*]在游戏内生成村民、编辑人物模板和配置谷密\n[*]批量关系、传剑继承与轮回信息注入\n[*]F9 面板内保存全部详细设置\n[*]支持中文与 English 界面\n[/list]\n\n[code]\n功能             入口\n村民生成         人物工坊／村民生成\n人物模板         人物工坊／模板编辑\n谷密设置         人物工坊／谷密\n传剑与轮回       人物工坊／传剑与转世\n[/code]\n\n[warn]测试轮回与关系功能前请备份存档。[/warn]",
    Source = 0,
    GameVersion = "1.0.44",
    BackendPlugins = { [1] = "CharacterStudio.Backend.dll" },
    FrontendPlugins = { [1] = "CharacterStudio.Frontend.dll" },
    Visibility = 2,
    SettingGroups = { [1] = "功能开关", [2] = "快捷键", [3] = "诊断" },
    DefaultSettings = {
        {
            SettingType = "Toggle", Key = "EnableCustomVillagers",
            DisplayName = "自定义村民", GroupName = "功能开关",
            Description = "Enable custom villager generation and village processing.",
            DefaultValue = true,
        },
        {
            SettingType = "Toggle", Key = "EnableCustomCloseFriends",
            DisplayName = "自定义谷密", GroupName = "功能开关",
            Description = "Enable close-friend customization configured in the in-game studio.",
            DefaultValue = true,
        },
        {
            SettingType = "Toggle", Key = "EnableLegacyFeatures",
            DisplayName = "传剑与转世", GroupName = "功能开关",
            Description = "Enable legacy passing, inheritance and previous-identity features.",
            DefaultValue = false,
        },
        {
            SettingType = "InputField", Key = "CharacterStudioPanelKey",
            DisplayName = "人物工坊快捷键", GroupName = "快捷键",
            Description = "Hotkey used to open or close the in-game studio.",
            DefaultValue = "F9",
        },
        {
            SettingType = "InputField", Key = "ImmediateLegacyPassingKey",
            DisplayName = "即刻传剑快捷键", GroupName = "快捷键",
            Description = "Hotkey used to request the original legacy-passing flow.",
            DefaultValue = "T",
        },
        {
            SettingType = "Toggle", Key = "EnableDebugLog",
            DisplayName = "调试日志", GroupName = "诊断",
            Description = "Write detailed diagnostic messages.",
            DefaultValue = true,
        },
        {
            SettingType = "Toggle", Key = "LogValueSnapshots",
            DisplayName = "数值快照", GroupName = "诊断",
            Description = "Log before, target and final attribute values.",
            DefaultValue = true,
        },
    },
    ChangeConfig = false,
    HasArchive = false,
    NeedRestartWhenSettingChanged = false,
}
