return {
    Title = "人物工坊",
    Author = "WQHH",
    Version = "0.1.0",
    Description = "统一的人物创建与定制工具。F9 打开村民创建面板。所有高影响功能均可独立关闭。",
    Source = 0,
    GameVersion = "1.0.32",
    BackendPlugins = { [1] = "CharacterStudio.Backend.dll" },
    FrontendPlugins = { [1] = "CharacterStudio.Frontend.dll" },
    Visibility = 2,
    DefaultSettings = {
        { SettingType="Toggle", Key="EnableMod", DisplayName="【总开关】启用人物工坊", DefaultValue=true },
        { SettingType="Toggle", Key="InfiniteCreationPoints", DisplayName="【太吾创建】解除创建点数限制", DefaultValue=false },
        { SettingType="Toggle", Key="CustomizeProtagonist", DisplayName="【太吾创建】应用统一人物档案", Description="创建完成后应用下方属性、资质、健康和特性配置。", DefaultValue=false },
        { SettingType="Toggle", Key="CustomizeCloseFriend", DisplayName="【谷中密友】应用统一人物档案", DefaultValue=true },
        { SettingType="InputField", Key="CloseFriendCount", DisplayName="【谷中密友】生成数量", Description="1-10；仅在新建存档时生效。", DefaultValue="1" },
        { SettingType="Toggle", Key="CustomizeCreatedVillagers", DisplayName="【村民创建】应用统一人物档案", DefaultValue=true },
        { SettingType="Toggle", Key="CustomizeInitialVillagers", DisplayName="【初始村民】应用统一人物档案", Description="不替换原版家庭生成，只在原版创建人物时定制字段。", DefaultValue=false },
        { SettingType="Toggle", Key="ExpandVillageCapacity", DisplayName="【村民创建】自动扩展人口容量", DefaultValue=true },
        { SettingType="InputField", Key="VillageCapacity", DisplayName="【村民创建】目标人口容量", DefaultValue="500" },
        { SettingType="Dropdown", Key="AttributeMode", DisplayName="【数值档案】应用模式", Description="0=保持原值，1=仅提高到目标值，2=强制覆盖。", Options={"保持原值","最低值","覆盖值"}, DefaultValue=1 },
        { SettingType="InputField", Key="MainAttributeValue", DisplayName="【数值档案】六维目标值", DefaultValue="100" },
        { SettingType="InputField", Key="LifeQualificationValue", DisplayName="【数值档案】技艺资质目标值", DefaultValue="100" },
        { SettingType="InputField", Key="CombatQualificationValue", DisplayName="【数值档案】武学资质目标值", DefaultValue="100" },
        { SettingType="InputField", Key="BaseHealth", DisplayName="【数值档案】健康上限", Description="0 表示不修改。", DefaultValue="0" },
        { SettingType="InputField", Key="Morality", DisplayName="【数值档案】道德值", Description="-1 表示不修改。", DefaultValue="-1" },
        { SettingType="InputField", Key="FeatureIds", DisplayName="【特性档案】添加特性 ID", Description="逗号分隔；只使用已确认 ID。", DefaultValue="" },
        { SettingType="InputField", Key="RemoveFeatureIds", DisplayName="【特性档案】移除特性 ID", Description="逗号分隔。", DefaultValue="" },
        { SettingType="Toggle", Key="Bisexual", DisplayName="【人物档案】设为双性恋（实验性）", Description="使用版本相关私有字段，默认关闭。", DefaultValue=false },
        { SettingType="InputField", Key="RelationType", DisplayName="【关系档案】与太吾关系位值", Description="0 表示不建立关系；8192 通常为朋友。", DefaultValue="8192" },
        { SettingType="InputField", Key="Favorability", DisplayName="【关系档案】与太吾好感", DefaultValue="30000" },
        { SettingType="Dropdown", Key="DefaultGender", DisplayName="【面板默认】性别", Options={"女","男","随机"}, DefaultValue=2 },
        { SettingType="InputField", Key="DefaultAge", DisplayName="【面板默认】年龄", DefaultValue="18" },
        { SettingType="InputField", Key="DefaultAttraction", DisplayName="【面板默认】魅力", DefaultValue="550" },
        { SettingType="InputField", Key="DefaultSurname", DisplayName="【面板默认】姓氏", DefaultValue="" },
        { SettingType="InputField", Key="DefaultGivenName", DisplayName="【面板默认】名字", DefaultValue="" },
        { SettingType="Dropdown", Key="BodyTypeChoice", DisplayName="【人物档案】身体类型", Description="保持原值或选择游戏身体类型 0-2。", Options={"保持原值","类型 0","类型 1","类型 2"}, DefaultValue=0 },
        { SettingType="InputField", Key="ClothingTemplateId", DisplayName="【人物档案】服装模板 ID", Description="0 表示不修改。", DefaultValue="0" },
        { SettingType="Toggle", Key="EnableDebugLog", DisplayName="【诊断】输出调试日志", DefaultValue=true },
    },
    ChangeConfig = false,
    HasArchive = false,
    NeedRestartWhenSettingChanged = false,
}
